### ISSUE TITLE
Spoofing

### ISSUE THREAD

**Issue by martinssipenko** [middlewares/client-ip#11]
Hi,

Correct me if I'm  but it looks like if client sends `X-Forwarded-For: 1.2.3.4, 5.6.7.8` in request, which then goes via trusted proxy (or several), and middleware is configured using `proxy(['ip of trusted proxy'])` then the result is that client Ip appears as `1.2.3.4`, however the actual client IP (detected by first proxy) should be the 3rd in the XFF list.

In other words, the middleware should check XFF IP addresses one by one from right to left, and return first one that is not in the trusted proxies list.

**Comment by oscarotero** [comment]
Yes, you're absolutely correct. Thanks for address this.
Do you like to work in a PR? If don't, I can fix it.

**Comment by martinssipenko** [comment]
@oscarotero check out the PR above.
