### ISSUE TITLE
Handle IPv6 With Port

### ISSUE THREAD

**Issue by mattsah** [middlewares/client-ip#16]
This might be outside the scope of this, but I think it would be a good feature.  When using IPv6 addresses on non standard ports, PHP's REMOTE_ADDR does not strip the brackets.  This can be hacked around with something like:

```
$_SERVER['REMOTE_ADDR'] = trim($_SERVER['REMOTE_ADDR'], '[]');
```

It might be useful to have this library simply trim [] similarly to set the client-ip.  Thoughts?

**Comment by oscarotero** [comment]
This seems to be a php bug https://bugs.php.net/bug.php?id=76919
Would you like to work on a PR?

**Comment by mattsah** [comment]
Yes, I can work on a PR -- just waned to make sure it was something you were interested in first.

**Comment by mattsah** [comment]
Added pull request #17 to handle this.  I don't think there's much danger or problem stripping the brackets regardless of any match.  I put this in the changelog as 1.3.0 because although it solves a bug, the bug is not in the project, and handling the workaround seems like a new feature per semver.

**Comment by oscarotero** [comment]
Thank you!
