### ISSUE TITLE
Wrong header parsing order

### ISSUE THREAD

**Issue by arokettu** [middlewares/client-ip#18]
According to the (unofficial) spec, X-Forwarded-For format is the following:

```
X-Forwarded-For: client, proxy1, proxy2
```

https://en.wikipedia.org/wiki/X-Forwarded-For#Format

but the library will return proxy2. This contradicts the spec and behavior of other libraries like Symfony's HttpFoundation

Solution: remove array_reverse in header parsing

**Comment by oscarotero** [comment]
Hi, thanks for notify this.
One question: seems like this order is only for `X-Forwarded-For` header but not `X-Forwarder`, right?
If you want to work on a PR, I'd appreciate that. If not, don't worry, I can fix it but I don't have much free time for now.

**Comment by arokettu** [comment]
Probably invalid issue, #11
