### ISSUE TITLE
Tests should not make external requests

### ISSUE THREAD

**Issue by shadowhand** [middlewares/client-ip#6]
The testing is not mocking the [`file_get_contents` call for remote IP fetching](https://github.com/middlewares/client-ip/blob/728e89e771245668e9047392109672664564e2e4/src/ClientIp.php#L111), which makes the unit tests dependent on an external service. No bueño.

**Comment by oscarotero** [comment]
I'm agree, but how can this be mocked? I'm not acquainted with mock libraries for testing.

**Comment by shadowhand** [comment]
I'll make a PR.
