### ISSUE TITLE
Forwarded header

### ISSUE THREAD

**Issue by ncou** [middlewares/client-ip#9]
Hi,

I was looking at your code and i have a question : are you sure there will not be a problem when the "forwarded" header is present ?

I was looking at the specs and it looks like the forwarded header use a keyword "for=" to add the ip. it even use bracket for ipv6.
In you code, i think the isValid() function will return false because it will test the string header value "for=80.80.80.80" instead of "80.80.80.80".

Am i missing something ?

**Comment by oscarotero** [comment]
Yes, you're right. `Forwarded` and `X-Forwarded` headers should work differently, getting the `for` directives.
Thanks for warning!

**Comment by oscarotero** [comment]
v1.0.1 released including a bugfix for this.
thanks

**Comment by ncou** [comment]
no problem :)
by the way, your work on middlewares have been a huge source of inspiration because i am thinking to create a microframework.
Do you think once i have a stable version you could give an eyes ? I think you feedbacks could help me to improve it.

In any case keep up the good work.

**Comment by oscarotero** [comment]
Yes, no problem
